### ISSUE TITLE
Might be missing formula (Abolute Deviation section)

### ISSUE THREAD

**Issue by sandgate-dev** [learn-co-curriculum/dsc-1-02-15-measures-of-dispersion-summary#3]
It says 

> ...as shown in the formula below:

but there is none to be seen.

**Comment by sandgate-dev** [comment]
Mean Deviation formula:
![mad](https://user-images.githubusercontent.com/18425964/46413918-ed0d9400-c719-11e8-9b07-acfadc1491b6.jpg)

**Comment by PeterBell** [comment]
Hi @osterburg are you still seeing that issue? It's displaying fine for me at the moment...

**Comment by sandgate-dev** [comment]
Looks good, thx.
